"use client"

import React from 'react'

export function ClientHealthAndTest() {
  const [health, setHealth] = React.useState<string>('')

  React.useEffect(() => {
    fetch('/api/health').then(async r => {
      if (!r.ok) throw new Error(String(r.status))
      const j = await r.json()
      setHealth(j?.status === 'ok' ? 'OK' : 'Unknown')
    }).catch(()=> setHealth('Unavailable'))
  }, [])

  // In-app summarize disabled: extension-only flow

  return (
    <div className="bg-white rounded-xl border border-gray-200 p-6 mb-8">
      <h2 className="text-xl font-semibold text-gray-900 mb-3">Live Check</h2>
      <p className="text-sm text-gray-600 mb-3">Summaries are generated by the Chrome extension only.</p>
      <span className={`inline-flex items-center px-2 py-1 rounded-full text-sm ${health==='OK' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
        API Health: {health || '...'}
      </span>
    </div>
  )
}


